'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import styles from './admin.module.css';
import { CK_RESTAURANT_ID, supabase } from '../../lib/supabase/client';

type DbStatus = 'new'|'confirmed'|'completed'|'cancelled'|'no_show';
type Status = 'Nova'|'Confirmada'|'Concluída'|'Cancelada'|'Não compareceu';
type Role = 'owner'|'manager'|'staff';
type Reservation = { id:string; date:string; day:number; time:string; name:string; phone:string; people:number; status:Status; lastVisit:number|null; visits:number };
type Customer = { id:string; name:string; phone:string; lastVisit:number|null; visits:number };
type Rule = { id:string; weekday:number; is_open:boolean; capacity:number };

const week=['DOM','SEG','TER','QUA','QUI','SEX','SÁB'];
const months=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
const toLabel:Record<DbStatus,Status>={new:'Nova',confirmed:'Confirmada',completed:'Concluída',cancelled:'Cancelada',no_show:'Não compareceu'};
const toDb:Record<Status,DbStatus>={Nova:'new',Confirmada:'confirmed',Concluída:'completed',Cancelada:'cancelled','Não compareceu':'no_show'};
const LOGIN_GUARD_KEY='ck-crm-login-guard-v1',LOGIN_MAX_ATTEMPTS=5,LOGIN_LOCK_MS=15*60*1000;
type LoginGuard={failures:number;windowStarted:number;lockedUntil:number};
function readLoginGuard():LoginGuard{try{return JSON.parse(localStorage.getItem(LOGIN_GUARD_KEY)||'null')||{failures:0,windowStarted:Date.now(),lockedUntil:0}}catch{return{failures:0,windowStarted:Date.now(),lockedUntil:0}}}
function offsetDate(offset:number){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return d}
function dateValue(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function daysSince(value:string|null){return value?Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000)):null}
function returnLabel(days:number|null){if(days===null)return'Primeira visita';if(days===0)return'Visitou hoje';if(days===1)return'Há 1 dia';if(days<30)return`Há ${days} dias`;if(days<365)return`Há ${Math.floor(days/30)} meses`;return`Há ${Math.floor(days/365)} ano${days>=730?'s':''}`}

function ReservationRow({item,onStatus}:{item:Reservation;onStatus:(id:string,status:Status)=>void}){const [year,month,day]=item.date.split('-');return <article className={styles.row}>
  <time>{item.time}<small>{day}/{month}/{year}</small></time><div className={styles.client}><i>{item.name.split(' ').map(p=>p[0]).slice(0,2).join('')}</i><div><b>{item.name}</b><small>{item.phone} · {item.visits} visita{item.visits===1?'':'s'}</small></div></div>
  <div className={`${styles.lastVisit} ${(item.lastVisit??0)>=90?styles.inactive:''}`}><b>{returnLabel(item.lastVisit)}</b><small>{(item.lastVisit??0)>=90?'Reativar cliente':'Cliente recente'}</small></div><strong>{item.people}<small> pessoas</small></strong>
  <select value={item.status} onChange={e=>onStatus(item.id,e.target.value as Status)} data-status={item.status}>{Object.values(toLabel).map(s=><option key={s}>{s}</option>)}</select><a href={`https://wa.me/55${item.phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp</a>
</article>}
function Empty(){return <div className={styles.empty}><b>Nenhuma reserva encontrada</b><span>Este dia está livre ou a busca não encontrou clientes.</span></div>}

export default function AdminPage(){
  const [access,setAccess]=useState<'loading'|'signedout'|'unauthorized'|'ready'>('loading');
  const [profile,setProfile]=useState<{name:string;role:Role}|null>(null);
  const [authError,setAuthError]=useState('');const [authLoading,setAuthLoading]=useState(false);const [dataLoading,setDataLoading]=useState(false);
  const [section,setSection]=useState('Visão geral');const [day,setDay]=useState(0);const [reservations,setReservations]=useState<Reservation[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [rules,setRules]=useState<Record<number,Rule>>({});const [blockedDates,setBlockedDates]=useState<string[]>([]);const [blockedSlots,setBlockedSlots]=useState<string[]>([]);const [search,setSearch]=useState('');const [toast,setToast]=useState('');
  const dates=useMemo(()=>Array.from({length:7},(_,i)=>offsetDate(i)),[]);const date=dates[day];const selectedDate=dateValue(date);const rule=rules[date.getDay()];const capacity=rule?.capacity??42;const current=reservations.filter(r=>r.day===day&&r.status!=='Cancelada');const visible=current.filter(r=>`${r.name} ${r.phone}`.toLowerCase().includes(search.toLowerCase()));const people=current.reduce((n,r)=>n+r.people,0);const inactive=customers.filter(c=>(c.lastVisit??0)>=90).length;const weeklyClosed=rule?!rule.is_open:date.getDay()===1;const isBlocked=weeklyClosed||blockedDates.includes(selectedDate);const canManage=profile?.role==='owner'||profile?.role==='manager';
  function notify(text:string){setToast(text);window.setTimeout(()=>setToast(''),2600)}

  const loadData=useCallback(async()=>{setDataLoading(true);const from=dateValue(dates[0]),to=dateValue(dates[6]),reservationTo=dateValue(offsetDate(180));const [rr,cr,ar,dr,sr]=await Promise.all([
    supabase.from('reservations').select('id,reservation_date,reservation_time,party_size,status,customer:customers!reservations_customer_id_fkey(name,phone,last_visit_at,visit_count)').eq('restaurant_id',CK_RESTAURANT_ID).gte('reservation_date',from).lte('reservation_date',reservationTo).order('reservation_date').order('reservation_time'),
    supabase.from('customers').select('id,name,phone,last_visit_at,visit_count').eq('restaurant_id',CK_RESTAURANT_ID).order('updated_at',{ascending:false}).limit(300),
    supabase.from('availability_rules').select('id,weekday,is_open,capacity').eq('restaurant_id',CK_RESTAURANT_ID),
    supabase.from('blocked_dates').select('blocked_date').eq('restaurant_id',CK_RESTAURANT_ID).gte('blocked_date',from).lte('blocked_date',to),
    supabase.from('blocked_slots').select('blocked_date,blocked_time').eq('restaurant_id',CK_RESTAURANT_ID).gte('blocked_date',from).lte('blocked_date',to)
  ]);const error=[rr.error,cr.error,ar.error,dr.error,sr.error].find(Boolean);if(error){notify(`Não foi possível carregar os dados: ${error.message}`);setDataLoading(false);return}
    setReservations((rr.data??[]).map(row=>{const raw=Array.isArray(row.customer)?row.customer[0]:row.customer;const c=raw as {name:string;phone:string;last_visit_at:string|null;visit_count:number}|null;return{id:row.id,date:row.reservation_date,day:dates.findIndex(d=>dateValue(d)===row.reservation_date),time:String(row.reservation_time).slice(0,5),name:c?.name??'Cliente',phone:c?.phone??'',people:row.party_size,status:toLabel[row.status as DbStatus],lastVisit:daysSince(c?.last_visit_at??null),visits:c?.visit_count??0}}));
    setCustomers((cr.data??[]).map(c=>({id:c.id,name:c.name,phone:c.phone,lastVisit:daysSince(c.last_visit_at),visits:c.visit_count})));setRules(Object.fromEntries((ar.data??[]).map(r=>[r.weekday,r as Rule])));setBlockedDates((dr.data??[]).map(r=>r.blocked_date));setBlockedSlots((sr.data??[]).map(s=>`${s.blocked_date}|${String(s.blocked_time).slice(0,5)}`));setDataLoading(false)
  },[dates]);

  useEffect(()=>{async function verify(){const {data:{session}}=await supabase.auth.getSession();if(!session){setAccess('signedout');setProfile(null);return}const {data}=await supabase.from('staff_profiles').select('full_name,role').eq('user_id',session.user.id).eq('restaurant_id',CK_RESTAURANT_ID).maybeSingle();if(!data){setAccess('unauthorized');return}setProfile({name:data.full_name||session.user.email||'Equipe CK Sushi',role:data.role as Role});setAccess('ready');void loadData()}void verify();const {data:l}=supabase.auth.onAuthStateChange(()=>void verify());return()=>l.subscription.unsubscribe()},[loadData]);
  useEffect(()=>{if(access!=='ready')return;const refresh=()=>void loadData();const interval=window.setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{window.clearInterval(interval);window.removeEventListener('focus',refresh)}},[access,loadData]);
  async function login(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const now=Date.now();let guard=readLoginGuard();
    if(guard.lockedUntil>now){const minutes=Math.max(1,Math.ceil((guard.lockedUntil-now)/60000));setAuthError(`Muitas tentativas. Tente novamente em ${minutes} minuto${minutes===1?'':'s'}.`);return}
    if(now-guard.windowStarted>LOGIN_LOCK_MS)guard={failures:0,windowStarted:now,lockedUntil:0};
    const f=new FormData(e.currentTarget);setAuthLoading(true);setAuthError('');
    const {error}=await supabase.auth.signInWithPassword({email:String(f.get('email')||''),password:String(f.get('password')||'')});
    if(error){const failures=guard.failures+1,lockedUntil=failures>=LOGIN_MAX_ATTEMPTS?now+LOGIN_LOCK_MS:0;localStorage.setItem(LOGIN_GUARD_KEY,JSON.stringify({failures,windowStarted:guard.windowStarted,lockedUntil}));const remaining=Math.max(0,LOGIN_MAX_ATTEMPTS-failures);setAuthError(lockedUntil?'Limite de 5 tentativas atingido. Login bloqueado por 15 minutos.':`E-mail ou senha inválidos. ${remaining} tentativa${remaining===1?'':'s'} restante${remaining===1?'':'s'}.`)}else localStorage.removeItem(LOGIN_GUARD_KEY);
    setAuthLoading(false)
  }
  async function setStatus(id:string,status:Status){const old=reservations;setReservations(rs=>rs.map(r=>r.id===id?{...r,status}:r));const {error}=await supabase.from('reservations').update({status:toDb[status],updated_at:new Date().toISOString()}).eq('id',id).eq('restaurant_id',CK_RESTAURANT_ID);if(error){setReservations(old);notify(`Alteração não salva: ${error.message}`)}else notify(`Reserva marcada como ${status.toLowerCase()}.`)}
  async function toggleDate(target:Date){if(!canManage){notify('Somente proprietário ou gerente pode alterar a disponibilidade.');return}const value=dateValue(target),blocked=blockedDates.includes(value);const request=blocked?supabase.from('blocked_dates').delete().eq('restaurant_id',CK_RESTAURANT_ID).eq('blocked_date',value):supabase.from('blocked_dates').insert({restaurant_id:CK_RESTAURANT_ID,blocked_date:value});const {error}=await request;if(error){notify(`Alteração não salva: ${error.message}`);return}setBlockedDates(ds=>blocked?ds.filter(d=>d!==value):[...ds,value]);notify(blocked?'Data liberada.':'Data bloqueada.')}
  async function toggleSlot(time:string){if(!canManage){notify('Somente proprietário ou gerente pode bloquear horários.');return}const key=`${selectedDate}|${time}`,blocked=blockedSlots.includes(key);const request=blocked?supabase.from('blocked_slots').delete().eq('restaurant_id',CK_RESTAURANT_ID).eq('blocked_date',selectedDate).eq('blocked_time',time):supabase.from('blocked_slots').insert({restaurant_id:CK_RESTAURANT_ID,blocked_date:selectedDate,blocked_time:time});const {error}=await request;if(error){notify(`Alteração não salva: ${error.message}`);return}setBlockedSlots(ss=>blocked?ss.filter(s=>s!==key):[...ss,key]);notify(blocked?'Horário liberado.':'Horário bloqueado.')}
  async function updateCapacity(weekday:number,value:number){if(!canManage){notify('Somente proprietário ou gerente pode alterar a capacidade.');return}const target=rules[weekday];if(!target)return;const next=Math.max(1,Math.min(500,value));setRules(rs=>({...rs,[weekday]:{...target,capacity:next}}));const {error}=await supabase.from('availability_rules').update({capacity:next}).eq('id',target.id);if(error){setRules(rs=>({...rs,[weekday]:target}));notify(`Capacidade não salva: ${error.message}`)}else notify('Capacidade atualizada.')}

  if(access==='loading')return <main className={styles.authPage}><div className={styles.authCard}><img className={styles.authMark} src="/ck-logo.png" alt="CK Sushi"/><p>Verificando acesso seguro…</p></div></main>;
  if(access==='signedout')return <main className={styles.authPage}><form className={styles.authCard} onSubmit={login}><img className={styles.authMark} src="/ck-logo.png" alt="CK Sushi"/><small>CK SUSHI · ÁREA RESTRITA</small><h1>Entrar no<br/>painel.</h1><label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha<input name="password" type="password" autoComplete="current-password" required/></label>{authError&&<p className={styles.authError}>{authError}</p>}<button disabled={authLoading}>{authLoading?'Entrando…':'Entrar com segurança'}</button><Link href="/">Voltar ao site</Link></form></main>;
  if(access==='unauthorized')return <main className={styles.authPage}><div className={styles.authCard}><img className={styles.authMark} src="/ck-logo.png" alt="CK Sushi"/><small>ACESSO NÃO AUTORIZADO</small><h1>Conta sem<br/>permissão.</h1><p>Este usuário existe, mas não está cadastrado como funcionário do CK Sushi.</p><button onClick={()=>supabase.auth.signOut()}>Sair desta conta</button></div></main>;

  const table=(items:Reservation[])=><><div className={styles.head}><span>Horário</span><span>Cliente</span><span>Última visita</span><span>Pessoas</span><span>Status</span><span>Contato</span></div><div>{items.length?items.map(r=><ReservationRow key={r.id} item={r} onStatus={setStatus}/>):<Empty/>}</div></>;
  return <main className={styles.shell}><aside className={styles.sidebar}><Link className={styles.brand} href="/"><img src="/ck-logo.png" alt="CK Sushi"/><div><small>GESTÃO</small></div></Link><nav>{[['Visão geral','⌂'],['Agenda','◦'],['Reservas','◎'],['Clientes','♙'],['Disponibilidade','◇']].map(([name,icon])=><button key={name} className={section===name?styles.active:''} onClick={()=>setSection(name)}><i>{icon}</i><span>{name}</span></button>)}</nav><div className={styles.profile}><span>{profile?.name.split(' ').map(p=>p[0]).slice(0,2).join('')}</span><div><b>{profile?.name}</b><small>{profile?.role==='owner'?'Proprietário':profile?.role==='manager'?'Gerente':'Equipe'}</small></div><button className={styles.signOut} onClick={()=>supabase.auth.signOut()}>Sair</button></div></aside>
  <section className={styles.content}><header className={styles.topbar}><div><p>CK SUSHI · VOTORANTIM</p><h1>{section}</h1></div><div><span>{dataLoading?'Atualizando…':'Dados do Supabase'}</span><button disabled={dataLoading} onClick={()=>void loadData()}>↻ Atualizar</button><button onClick={()=>window.location.assign('/?reservar=1')}>＋ Nova reserva</button></div></header>
  {(section==='Visão geral'||section==='Agenda'||section==='Disponibilidade')&&<section className={styles.weekbar}><div><small>AGENDA DA SEMANA</small><b>{months[date.getMonth()]} de {date.getFullYear()}</b></div><nav>{dates.map((d,i)=>{const count=reservations.filter(r=>r.day===i&&r.status!=='Cancelada').length,closed=!(rules[d.getDay()]?.is_open??d.getDay()!==1)||blockedDates.includes(dateValue(d));return <button key={d.toISOString()} onClick={()=>setDay(i)} className={`${day===i?styles.dayActive:''} ${closed?styles.dayBlocked:''}`}><small>{i===0?'HOJE':week[d.getDay()]}</small><b>{d.getDate()}</b><span>{closed?'Fechado':`${count} reserva${count===1?'':'s'}`}</span></button>})}</nav></section>}
  {section==='Visão geral'&&<><section className={styles.stats}><article><i>◎</i><div><small>RESERVAS DO DIA</small><b>{current.length}</b><span>{current.filter(r=>r.status==='Confirmada').length} confirmadas</span></div></article><article><i>♙</i><div><small>PESSOAS ESPERADAS</small><b>{people}</b><span>de {capacity} lugares</span></div></article><article><i>◇</i><div><small>CLIENTES INATIVOS</small><b>{inactive}</b><span>há mais de 90 dias</span></div></article><article><i>{isBlocked?'×':'✓'}</i><div><small>DISPONIBILIDADE</small><b>{isBlocked?'Fechado':`${Math.max(capacity-people,0)} vagas`}</b><span>{isBlocked?'data bloqueada':'restantes'}</span></div></article></section><div className={styles.grid}><section className={styles.panel}><header><div><small>{week[date.getDay()]}, {date.getDate()} DE {months[date.getMonth()].toUpperCase()}</small><h2>Reservas do dia</h2></div><label>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente"/></label></header>{table(visible)}</section><aside className={styles.availability}><small>CONTROLE DO DIA</small><h2>Disponibilidade</h2><div className={styles.ring} style={{'--fill':`${Math.min(100,people/capacity*100)}%`} as React.CSSProperties}><span><b>{people}</b>de {capacity}</span></div><label>Capacidade máxima<div><button disabled={!canManage} onClick={()=>void updateCapacity(date.getDay(),capacity-1)}>−</button><input type="number" value={capacity} disabled={!canManage} onChange={e=>void updateCapacity(date.getDay(),Number(e.target.value))}/><button disabled={!canManage} onClick={()=>void updateCapacity(date.getDay(),capacity+1)}>＋</button></div></label><button className={isBlocked?styles.release:styles.block} disabled={weeklyClosed||!canManage} onClick={()=>void toggleDate(date)}>{weeklyClosed?'Fechado pela regra semanal':isBlocked?'Liberar esta data':'Bloquear esta data'}</button><p>Alterações são salvas no Supabase e refletidas nas novas reservas.</p></aside></div></>}
  {section==='Agenda'&&<section className={styles.fullPanel}><header className={styles.sectionHead}><div><small>VISÃO POR HORÁRIO</small><h2>Agenda de {date.getDate()} de {months[date.getMonth()]}</h2></div><span>{weeklyClosed?'Fechado pela regra semanal':isBlocked?'Data bloqueada':'Recebendo reservas'}</span></header><div className={styles.timeline}>{['18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00'].map(time=>{const bookings=current.filter(r=>r.time===time),closed=blockedSlots.includes(`${selectedDate}|${time}`);return <article key={time} className={closed?styles.slotClosed:''}><time>{time}</time><div>{bookings.length?bookings.map(r=><span key={r.id}><b>{r.name}</b><small>{r.people} pessoas · {r.status}</small></span>):<span><b>{closed?'Horário indisponível':'Horário livre'}</b><small>{closed?'Bloqueado pela equipe':`${Math.max(capacity-people,0)} vagas no dia`}</small></span>}</div><button disabled={!canManage||weeklyClosed} onClick={()=>void toggleSlot(time)}>{closed?'Liberar':'Bloquear'}</button></article>})}</div></section>}
  {section==='Reservas'&&<section className={styles.fullPanel}><header className={styles.sectionHead}><div><small>SOLICITAÇÕES DA SEMANA</small><h2>Gestão de reservas</h2></div><label className={styles.globalSearch}>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome ou telefone"/></label></header>{table(reservations.filter(r=>`${r.name} ${r.phone}`.toLowerCase().includes(search.toLowerCase())))}</section>}
  {section==='Clientes'&&<section className={styles.fullPanel}><header className={styles.sectionHead}><div><small>RELACIONAMENTO</small><h2>Histórico de clientes</h2></div><label className={styles.globalSearch}>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente"/></label></header><div className={styles.clientGrid}>{customers.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(search.toLowerCase())).map(c=><article key={c.id} className={(c.lastVisit??0)>=90?styles.inactiveCard:''}><div className={styles.clientAvatar}>{c.name.split(' ').map(p=>p[0]).slice(0,2).join('')}</div><div><h3>{c.name}</h3><p>{c.phone}</p></div><dl><div><dt>Visitas</dt><dd>{c.visits}</dd></div><div><dt>Última visita</dt><dd>{returnLabel(c.lastVisit)}</dd></div></dl><a href={`https://wa.me/55${c.phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">{(c.lastVisit??0)>=90?'Reativar pelo WhatsApp':'Conversar no WhatsApp'}</a></article>)}</div></section>}
  {section==='Disponibilidade'&&<section className={styles.fullPanel}><header className={styles.sectionHead}><div><small>REGRAS DA SEMANA</small><h2>Capacidade e bloqueios</h2></div><span>{canManage?'Alterações permitidas':'Somente leitura'}</span></header><div className={styles.availabilityGrid}>{dates.map(d=>{const r=rules[d.getDay()],cap=r?.capacity??42,booked=reservations.filter(x=>x.day===dates.indexOf(d)&&x.status!=='Cancelada').reduce((n,x)=>n+x.people,0),weekly=r?!r.is_open:d.getDay()===1,blocked=blockedDates.includes(dateValue(d));return <article key={d.toISOString()} className={weekly||blocked?styles.closedDate:''}><small>{week[d.getDay()]}</small><h3>{d.getDate()} de {months[d.getMonth()]}</h3><strong>{weekly||blocked?'Fechado':`${Math.max(cap-booked,0)} vagas`}</strong><p>{weekly?'Fechamento semanal':`${booked} pessoas · capacidade ${cap}`}</p><button disabled={weekly||!canManage} onClick={()=>void toggleDate(d)}>{weekly?'Fechado pela regra semanal':blocked?'Liberar data':'Bloquear data'}</button></article>})}</div><div className={styles.capacityWide}><div><small>CAPACIDADE DO DIA SELECIONADO</small><h3>{week[date.getDay()]} · {date.getDate()} de {months[date.getMonth()]}</h3></div><div><button disabled={!canManage} onClick={()=>void updateCapacity(date.getDay(),capacity-1)}>−</button><b>{capacity}</b><button disabled={!canManage} onClick={()=>void updateCapacity(date.getDay(),capacity+1)}>＋</button></div></div></section>}
  </section>{toast&&<div className={styles.toast}>✓ {toast}</div>}</main>
}
